version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}   # Load the secret key from the environment
    env_file:
      - ./backend/.env                     # Load environment variables for development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
