version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Ensure this is set
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
